# Generated by Django 3.0.8 on 2020-12-24 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singer',
            options={'ordering': ('name',), 'verbose_name': 'Испольнитель', 'verbose_name_plural': 'Исполнитель'},
        ),
        migrations.AddField(
            model_name='station',
            name='image',
            field=models.ImageField(blank=True, upload_to='stations'),
        ),
        migrations.AddField(
            model_name='track',
            name='image',
            field=models.ImageField(blank=True, upload_to='<django.db.models.fields.related.ForeignKey>/traks'),
        ),
    ]
