# Generated by Django 3.0.8 on 2020-12-24 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_auto_20201224_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.CharField(default='-', max_length=40),
        ),
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.DurationField(default=0),
        ),
        migrations.AlterField(
            model_name='track',
            name='ganre',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
