# Generated by Django 3.0.8 on 2020-12-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_auto_20201224_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
